import { Logo } from "@/components/Logo";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col justify-center h-full items-center">
          <Logo />
          <h1 className="text-3xl my-2">
            Bienvenido a mi DashBoard
          </h1>
          <h2 className="text-2xl mb-3">DashBoard Jhonatan</h2>
          {children}
        </div>
        </body>
    </html>
  )
}
